// /Quicksand → dipakai untuk body / teks umum (font-sans)
// Roboto Mono → dipakai untuk code / monospace (font-mono)
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Poppins, Quicksand, Roboto_Mono } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});
const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
});
const robotMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          poppins.variable,
          quicksand.variable,
          robotMono.variable,
          'font-sans antialiased'
        )}
      >
        {children}
      </body>
    </html>
  );
}
